#!/bin/sh

# Print environment variables for debugging
echo "GITHUB_TOKEN=${GITHUB_TOKEN}"
echo "GITHUB_USER=${GITHUB_USER}"
echo "GITHUB_REPO=${GITHUB_REPO}"
echo "GIT_USER_NAME=${GIT_USER_NAME}"
echo "GIT_USER_EMAIL=${GIT_USER_EMAIL}"
echo "SOURCE_PATH=${SOURCE_PATH}"
echo "TARGET_PATH=${TARGET_PATH}"

# Build the Docker image
docker build --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} \
             --build-arg GITHUB_USER=${GITHUB_USER} \
             --build-arg GITHUB_REPO=${GITHUB_REPO} \
             --build-arg GIT_USER_NAME=${GIT_USER_NAME} \
             --build-arg GIT_USER_EMAIL=${GIT_USER_EMAIL} \
             --build-arg SOURCE_PATH=${SOURCE_PATH} \
             --build-arg TARGET_PATH=${TARGET_PATH} \
             -t $IMAGE_NAME .
